name: test

on: [push, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install oss-cad-suite
        uses: YosysHQ/setup-oss-cad-suite@v2
        with:
          python-override: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Run simulation
        run: |
          iverilog -o tb.out src/*.v
          vvp tb.out


